### ISSUE TITLE
Question about rendering partial without assigning it to some key

### ISSUE THREAD

**Issue by yutakusuno** [thoughtbot/props_template#37]
I really appreciate your work. Is feature https://github.com/thoughtbot/props_template/pull/34 still a work in progress? It is already listed in the README as one of the features though.

```ruby
json.partial! partial: "posts/blog_post", locals: {post: @post} do
end
```

Thank you again. I am looking forward to using this wonderful gem 🤞

**Comment by jho406** [comment]
Hello and welcome! Thanks for commenting!

It's been merged, but I haven't had a chance to do a release yet. I'll make it a priority to do a release in the next few days.

**Comment by jho406** [comment]
[0.36.0](https://rubygems.org/gems/props_template) is released. Thanks!
